#
#  Makefile for yasa
#
#  should build all (docs, webpages, binaries)
#

.PHONY: clean distclean


all:
	@DIR=doc && cd "$$DIR" && echo "### make $@ in $$DIR .." && make $@
	@DIR=src && cd "$$DIR" && echo "### make $@ in $$DIR .." && make $@
	@DIR=www && cd "$$DIR" && echo "### make $@ in $$DIR .." && make $@

clean:
	@DIR=doc && cd "$$DIR" && echo "### make $@ in $$DIR .." && make $@
	@DIR=src && cd "$$DIR" && echo "### make $@ in $$DIR .." && make $@
	@DIR=www && cd "$$DIR" && echo "### make $@ in $$DIR .." && make $@

distclean:
	@DIR=doc && cd "$$DIR" && echo "### make $@ in $$DIR .." && make $@
	@DIR=src && cd "$$DIR" && echo "### make $@ in $$DIR .." && make $@
	@DIR=www && cd "$$DIR" && echo "### make $@ in $$DIR .." && make $@
